### ISSUE TITLE
Aggregation of attributes common to SimMachineDef/SimOperationDef

### ISSUE THREAD

**Issue by pefribeiro** [UoY-RoboStar/robosim-metamodel#2]
It seems that both SimMachineDef and SimOperationDef share the same attributes of `inputContext` and `outputContext`, so it would be nice, even for implementation reasons, to put these into a single EClass, say `SimContext` and then make both `SimMachineDef` and `SimOperationDef` subclass `SimContext` (in addition to their own other supertypes).

Similar observation applies to everything that has a `cycleDef` attribute, namely `SimModule`, `SimControllerDef`, `SimMachineDef` and `SimOperationDef`. There should be a new EClass, say of name `Cyclic`, and then all these EClasses should inherit this attribute via subclassing.

However, I'm not sure why a `SimOperationDef` has a `cycleDef` attribute. Does a `SimOperationDef` have its own cycle? I suppose it should not? as otherwise how will it be defined in the context of an operation call from within a `SimMachineDef`? Clarification is needed here @madielfilho.

**Comment by madielfilho** [comment]
> However, I'm not sure why a SimOperationDef has a cycleDef attribute. Does a SimOperationDef have its own cycle? I suppose it should not? as otherwise how will it be defined in the context of an operation call from within a SimMachineDef? Clarification is needed here @madielfilho.

An operation in RoboSim does not have its own cycle. Looking at the RoboSim metamodel here [https://github.com/robo-star/circus.robocalc.robosim.textual.parent/blob/master/circus.robocalc.robosim.textual/src/circus/robocalc/robosim/textual/RoboSim.xtext], I did not find the definition of SimOperationDef.

**Comment by pefribeiro** [comment]
> An operation in RoboSim does not have its own cycle. Looking at the RoboSim metamodel here [https://github.com/robo-star/circus.robocalc.robosim.textual.parent/blob/master/circus.robocalc.robosim.textual/src/circus/robocalc/robosim/textual/RoboSim.xtext], I did not find the definition of SimOperationDef.

Thanks for your input @madielfilho. There is currently no textual language to allow it (although I have implemented it myself), but the element `SimOperationDef` has been in the meta-model (.ecore) since October 2019 (https://github.com/robo-star/circus.robocalc.robosim.parent/commit/4b08e203006ee05673ab596129fe1382fddaf951#diff-bdcbf2e440ce03dca3342765afcd06d1R24). 

We do need a `SimOperationDef` element to define software operations for RoboSim, but I agree with you they do not have their own cycle. However, they do need to have `inputContext` and `outputContext` information to allow the correct semantics to be generated with inputs and outputs. Furthermore, we need validation rules to ensure that when those operations are used, in the calling context such inputs and outputs are required/defined appropriately (like in RoboChart).

**Comment by pefribeiro** [comment]
I wonder if you could also comment on the proposal to:

1. To merge those attributes `inputContext` and `outputContext` under a new single EClass `SimContext`, which is then subclassed by `SimMachineDef` and `SimOperationDef`.
2. To make the cycle attribute part of another EClass `Cyclic`, which is then subclassed by all classes that need a cycle.

**Comment by madielfilho** [comment]
> Thanks for your input @madielfilho. There is currently no textual language to allow it (although I have implemented it myself), but the element SimOperationDef has been in the meta-model (.ecore) since October 2019 (4b08e20#diff-bdcbf2e440ce03dca3342765afcd06d1R24).
Sorry about that, I didn't know.

> I wonder if you could also comment on the proposal to:
> 
>     To merge those attributes inputContext and outputContext under a new single EClass SimContext, which is then subclassed by SimMachineDef and SimOperationDef.
>     To make the cycle attribute part of another EClass Cyclic, which is then subclassed by all classes that need a cycle.
> 
I agree with all improvements. It would be nice.

**Comment by pefribeiro** [comment]
Closing this issue as this has been adopted a while ago via the `SimContext` abstract class.
